#!/bin/bash

#if [ $1 = "preconfigured" ]; then
#    exec /usr/sbin/sshd -D -e
#fi
# -D Do not detach and become daemon.
#  -e Write debug logs to standard error. This could be used for debugging.

set -Eeo pipefail

# shellcheck disable=2154
trap 's=$?; echo "$0: Error on line "$LINENO": $BASH_COMMAND"; exit $s' ERR

reArgsMaybe="^[^:[:space:]]+:.*$" # Smallest indication of attempt to use argument
reArgSkip='^([[:blank:]]*#.*|[[:blank:]]*)$' # comment or empty line

# Paths
userConfPath="/etc/sftp/users.conf"
userConfPathLegacy="/etc/sftp-users.conf"
userConfFinalPath="/var/run/sftp/users.conf"

tagv="tag05"

function log() {
    echo "[$0] $*" >&2
}

# Allow running other programs, e.g. bash
if [[ -z "$1" || "$1" =~ $reArgsMaybe ]]; then
    startSshd=true
else
    startSshd=false
fi

# Backward compatibility with legacy config path
if [ ! -f "$userConfPath" ] && [ -f "$userConfPathLegacy" ]; then
    mkdir -p "$(dirname $userConfPath)"
    ln -s "$userConfPathLegacy" "$userConfPath"
fi

# Create users only on first run
if [ ! -f "$userConfFinalPath" ]; then
    mkdir -p "$(dirname $userConfFinalPath)"

    if [ -f "$userConfPath" ]; then
        # Append mounted config to final config
        grep -v -E "$reArgSkip" < "$userConfPath" > "$userConfFinalPath"
    fi

    if $startSshd; then
        # Append users from arguments to final config
        for user in "$@"; do
            echo "$user" >> "$userConfFinalPath"
        done
    fi

    if [ -n "$VSS_USER" ]; then
        # Append users from environment variable to final config
        log "$tagv appending visus user to final config file"
        IFS=" " read -r -a usersFromEnv <<< "$VSS_USER"
        for user in "${usersFromEnv[@]}"; do
            echo "$user" >> "$userConfFinalPath"
        done
    fi
    
    if [ -n "$MNS_USER" ]; then
        # Append users from environment variable to final config
        log "$tagv appending mands user to final config file"
        IFS=" " read -r -a usersFromEnv <<< "$MNS_USER"
        for user in "${usersFromEnv[@]}"; do
            echo "$user" >> "$userConfFinalPath"
        done
    fi
    
    if [ -n "$KNN_USER" ]; then
        # Append users from environment variable to final config
        log "$tagv appending konan user to final config file"
        IFS=" " read -r -a usersFromEnv <<< "$KNN_USER"
        for user in "${usersFromEnv[@]}"; do
            echo "$user" >> "$userConfFinalPath"
        done
    fi
    
    if [ -n "$EO_USER" ]; then
        # Append users from environment variable to final config
        log "$tagv appending emberone user to final config file"
        IFS=" " read -r -a usersFromEnv <<< "$EO_USER"
        for user in "${usersFromEnv[@]}"; do
            echo "$user" >> "$userConfFinalPath"
        done
    fi
    
    #Special permissions for adam/EO and vss
    if [ -n "$VSS_USER" ]; then
	    log "$tagv Parsing VSS_USER data"
	    IFS=':' read -ra userargs <<< "$VSS_USER"
        vssuser="${userargs[0]}"
        usermod -g ssh -d /home "$vssuser"
    fi
    
    if [ -n "$EO_USER" ]; then
	    log "$tagv Parsing EO_USER data"
	    IFS=':' read -ra userargs <<< "$EO_USER"
        eouser="${userargs[0]}"
        usermod -g ssh -d /home "$eouser"
    fi

    # Check that we have users in config
    if [ -f "$userConfFinalPath" ] && [ "$(wc -l < "$userConfFinalPath")" -gt 0 ]; then
        # Import users from final conf file
        while IFS= read -r user || [[ -n "$user" ]]; do
            create-sftp-user "$user"
        done < "$userConfFinalPath"
    elif $startSshd; then
        log "FATAL: No users provided!"
        exit 3
    fi    

    # Generate unique ssh keys for this container, if needed
    if [ ! -f /etc/ssh/ssh_host_ed25519_key ]; then
        ssh-keygen -t ed25519 -f /etc/ssh/ssh_host_ed25519_key -N ''
    fi
    if [ ! -f /etc/ssh/ssh_host_rsa_key ]; then
        ssh-keygen -t rsa -b 4096 -f /etc/ssh/ssh_host_rsa_key -N ''
    fi

    # Restrict access from other users
    chmod 600 /etc/ssh/ssh_host_ed25519_key || true
    chmod 600 /etc/ssh/ssh_host_rsa_key || true
fi

# Source custom scripts, if any
if [ -d /etc/sftp.d ]; then
    for f in /etc/sftp.d/*; do
        if [ -x "$f" ]; then
            log "Running $f ..."
            $f
        else
            log "Could not run $f, because it's missing execute permission (+x)."
        fi
    done
    unset f
fi

if $startSshd; then
    log "$tagv Executing sshd"
    exec /usr/sbin/sshd -D -e
else
    log "Executing $*"
    exec "$@"
fi
